// flow-typed signature: 435e51f2123d23dfe03a2224ba2e475f
// flow-typed version: <<STUB>>/@types/express_v^4.0.36/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
