// flow-typed signature: cc443a19b8d7053231fb53a9aefa71a8
// flow-typed version: <<STUB>>/@types/node_v^8.0.19/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
