// flow-typed signature: 08584744c060e45aa7a892ab306534ad
// flow-typed version: <<STUB>>/@types/react_v^16.0.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
