// flow-typed signature: 8a5d3e7fdff0cddd457463ea09a075bd
// flow-typed version: <<STUB>>/@types/webpack-hot-middleware_v^2.15.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack-hot-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack-hot-middleware' {
  declare module.exports: any;
}
