// flow-typed signature: de41fc8719783b7177155a806eb016c9
// flow-typed version: <<STUB>>/@types/webpack-dev-middleware_v^1.9.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack-dev-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack-dev-middleware' {
  declare module.exports: any;
}
